document: feedback-pipeline-workload
version: 1
data:
  name: tdawson packages
  description: Troy Dawsons ELN Extras packages
  maintainer: tdawson

  packages:
  - qt5-qtwebengine

  labels:
  - eln-extras

